# Generated by Django 5.0.3 on 2025-05-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="designation",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="joining_date",
        ),
        migrations.AddField(
            model_name="employee",
            name="citizenship_document",
            field=models.FileField(
                blank=True,
                help_text="Upload citizenship document (PDF only)",
                null=True,
                upload_to="employee_documents/",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="dob",
            field=models.DateField(blank=True, null=True, verbose_name="Date of Birth"),
        ),
        migrations.AddField(
            model_name="employee",
            name="emergency_contact",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="nationality",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="position",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="employee_profiles/"
            ),
        ),
    ]
