# Generated by Django 5.0.3 on 2025-05-02 14:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_remove_branch_contact_number_remove_branch_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="position",
        ),
    ]
