# Generated by Django 5.0.3 on 2025-05-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_rename_course_interest_lead_nationality_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lead",
            name="status",
        ),
        migrations.AddField(
            model_name="lead",
            name="lead_source",
            field=models.CharField(
                choices=[
                    ("Website", "Website"),
                    ("Social Media", "Social Media"),
                    ("Referral", "Referral"),
                    ("Walk-in", "Walk-in"),
                    ("Phone Inquiry", "Phone Inquiry"),
                    ("Email", "Email"),
                    ("Event", "Event"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=50,
            ),
        ),
    ]
