# Generated by Django 4.2.9 on 2025-05-06 02:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_user_username_alter_user_email"),
    ]

    operations = []
