# Generated by Django 4.2.9 on 2025-05-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_remove_student_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="required_experience",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
