# Generated by Django 4.2.9 on 2025-05-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_auto_20250506_0210"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
    ]
