# Generated by Django 4.2.9 on 2025-05-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_job_location_job_required_experience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="location",
            field=models.CharField(default="Not specified", max_length=255),
        ),
        migrations.AlterField(
            model_name="job",
            name="required_experience",
            field=models.CharField(default="Not specified", max_length=255),
        ),
    ]
