# Generated by Django 4.2.9 on 2025-05-08 15:08

import api.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_alter_activitylog_user_alter_blog_author_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", api.models.UserManager()),
            ],
        ),
    ]
