# Generated by Django 4.2.9 on 2025-05-08 15:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_alter_user_managers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
    ]
