# Generated by Django 4.2.9 on 2025-05-08 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0018_alter_user_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lead",
            name="assigned_to",
        ),
        migrations.AddField(
            model_name="lead",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_leads_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
