# Generated by Django 5.0.3 on 2025-05-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_remove_employee_designation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="branch",
            name="contact_number",
        ),
        migrations.RemoveField(
            model_name="branch",
            name="email",
        ),
        migrations.AddField(
            model_name="branch",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="branch",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
