# Generated by Django 5.0.3 on 2025-05-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_remove_employee_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="joining_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
