# Generated by Django 5.0.3 on 2025-05-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_employee_joining_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="course",
        ),
        migrations.RemoveField(
            model_name="student",
            name="fee_status",
        ),
        migrations.AddField(
            model_name="student",
            name="age",
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name="student",
            name="comments",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="emergency_contact",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="father_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                default="Other",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="institution_name",
            field=models.CharField(
                default="Unknown", max_length=200, verbose_name="College/School Name"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="language_test",
            field=models.CharField(
                choices=[
                    ("IELTS", "IELTS"),
                    ("PTE", "PTE"),
                    ("TOEFL", "TOEFL"),
                    ("None", "None"),
                ],
                default="None",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="mother_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="nationality",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="parent_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="student_profiles/"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="resume",
            field=models.FileField(
                blank=True,
                help_text="Upload CV/Resume (PDF only)",
                null=True,
                upload_to="student_resumes/",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="enrollment_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
