# Generated by Django 5.0.3 on 2025-05-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_remove_student_course_remove_student_fee_status_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lead",
            old_name="course_interest",
            new_name="nationality",
        ),
        migrations.AddField(
            model_name="lead",
            name="courses_studied",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="gpa",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=3, null=True
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="interested_country",
            field=models.CharField(
                blank=True,
                choices=[
                    ("USA", "USA"),
                    ("UK", "UK"),
                    ("Canada", "Canada"),
                    ("Australia", "Australia"),
                    ("New Zealand", "New Zealand"),
                    ("Germany", "Germany"),
                    ("France", "France"),
                    ("Japan", "Japan"),
                    ("Singapore", "Singapore"),
                    ("South Korea", "South Korea"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="interested_course",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="interested_degree",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Diploma", "Diploma"),
                    ("Bachelor", "Bachelor"),
                    ("Master", "Master"),
                    ("PhD", "PhD"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="language_score",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="language_test",
            field=models.CharField(
                choices=[
                    ("None", "None"),
                    ("IELTS", "IELTS"),
                    ("TOEFL", "TOEFL"),
                    ("N1", "N1"),
                    ("N2", "N2"),
                    ("N3", "N3"),
                ],
                default="None",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="referred_by",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
