# Generated by Django 5.0.3 on 2025-05-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_remove_lead_status_lead_lead_source"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="location",
        ),
        migrations.AddField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("Full-Time", "Full-Time"),
                    ("Part-Time", "Part-Time"),
                    ("Contract", "Contract"),
                    ("Internship", "Internship"),
                    ("Remote", "Remote"),
                ],
                default="Full-Time",
                max_length=20,
            ),
        ),
    ]
