# Generated by Django 4.2.9 on 2025-05-06 02:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_activitylog"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default="user", max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="email address"),
        ),
    ]
