# Generated by Django 4.2.9 on 2025-05-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_auto_20250506_0210"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AddField(
            model_name="job",
            name="location",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="job",
            name="required_experience",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_type",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="job",
            name="salary_range",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="job",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
    ]
